import React, { useEffect, useState } from "react";
import { Chart } from "react-google-charts";
import axios from "../../../../../helpers/axios";



export const options = {
  title: "Annual Finance Report",
  subtitle: "Revenue generated by scrap and resell",
  hAxis: { title: "Months", titleTextStyle: { color: "#333" } },
  //   vAxis: { title: "Amount (in Rs.)", titleTextStyle: { color: "#333" } },
  vAxis: { minValue: 0 },
  chartArea: { width: "80%", height: "80%" },
  colors: ['#C62828', '#1565C0']
};

export default function App() {

  const [JanResellRevenue, setJanResellRevenue] = useState("");
  const [FebResellRevenue, setFebResellRevenue] = useState("");
  const [MarResellRevenue, setMarResellRevenue] = useState("");
  const [AprResellRevenue, setAprResellRevenue] = useState("");
  const [MayResellRevenue, setMayResellRevenue] = useState("");
  const [JunResellRevenue, setJunResellRevenue] = useState("");
  const [JulResellRevenue, setJulResellRevenue] = useState("");
  const [AugResellRevenue, setAugResellRevenue] = useState("");
  const [SepResellRevenue, setSepResellRevenue] = useState("");
  const [OctResellRevenue, setOctResellRevenue] = useState("");
  const [NovResellRevenue, setNovResellRevenue] = useState("");
  const [DecResellRevenue, setDecResellRevenue] = useState("");


  const [JanScrapRevenue, setJanScrapRevenue] = useState("");
  const [FebScrapRevenue, setFebScrapRevenue] = useState("");
  const [MarScrapRevenue, setMarScrapRevenue] = useState("");
  const [AprScrapRevenue, setAprScrapRevenue] = useState("");
  const [MayScrapRevenue, setMayScrapRevenue] = useState("");
  const [JunScrapRevenue, setJunScrapRevenue] = useState("");
  const [JulScrapRevenue, setJulScrapRevenue] = useState("");
  const [AugScrapRevenue, setAugScrapRevenue] = useState("");
  const [SepScrapRevenue, setSepScrapRevenue] = useState("");
  const [OctScrapRevenue, setOctScrapRevenue] = useState("");
  const [NovScrapRevenue, setNovScrapRevenue] = useState("");
  const [DecScrapRevenue, setDecScrapRevenue] = useState("");





  useEffect(() => {

    const getScrapRevenue = async () => {

      const res = await axios.get(`/scrap/getMonthsscrap`);
      setDecScrapRevenue(res.data.DecScrapRevenue);
      setNovScrapRevenue(res.data.NovScrapRevenue);
      setOctScrapRevenue(res.data.OctScrapRevenue);
      setSepScrapRevenue(res.data.SepScrapRevenue);
      setAugScrapRevenue(res.data.AugScrapRevenue);

      setJulScrapRevenue(res.data.JulScrapRevenue);
      setJunScrapRevenue(res.data.JunScrapRevenue);
      setMayScrapRevenue(res.data.MayScrapRevenue);
      setAprScrapRevenue(res.data.AprScrapRevenue);
      setMarScrapRevenue(res.data.MarScrapRevenue);
      setFebScrapRevenue(res.data.FebScrapRevenue);
      setJanScrapRevenue(res.data.JanScrapRevenue);


    };
    const getResellRevenue = async () => {

      const res = await axios.get(`/resell/getMonthsResell`);

      setDecResellRevenue(res.data.DecResellRevenue);
      setNovResellRevenue(res.data.NovResellRevenue);
      setOctResellRevenue(res.data.OctResellRevenue);
      setSepResellRevenue(res.data.SepResellRevenue);
      setAugResellRevenue(res.data.AugResellRevenue);

      setJulResellRevenue(res.data.JulResellRevenue);
      setJunResellRevenue(res.data.JunResellRevenue);
      setMayResellRevenue(res.data.MayResellRevenue);
      setAprResellRevenue(res.data.AprResellRevenue);
      setMarResellRevenue(res.data.MarResellRevenue);
      setFebResellRevenue(res.data.FebResellRevenue);
      setJanResellRevenue(res.data.JanResellRevenue);


    };

    // getProductExpense();
    getResellRevenue();
    getScrapRevenue();


  }, [])
  let JanTotalRevenue = JanResellRevenue + JanScrapRevenue;
  let FebTotalRevenue = FebResellRevenue + FebScrapRevenue;
  let MarTotalRevenue = MarResellRevenue + MarScrapRevenue;
  let AprTotalRevenue = AprResellRevenue + AprScrapRevenue;
  let MayTotalRevenue = MayResellRevenue + MayScrapRevenue;
  let JunTotalRevenue = JunResellRevenue + JunScrapRevenue;
  let JulTotalRevenue = JulResellRevenue + JulScrapRevenue;
  let AugTotalRevenue = AugResellRevenue + AugScrapRevenue;
  let SepTotalRevenue = SepResellRevenue + SepScrapRevenue;
  let OctTotalRevenue = OctResellRevenue + OctScrapRevenue;
  let NovTotalRevenue = NovResellRevenue + NovScrapRevenue;
  let DecTotalRevenue = DecResellRevenue + DecScrapRevenue;

  const data = [
    ["Month", "Revenue"],
    ["January", JanTotalRevenue],
    ["February", FebTotalRevenue],
    ["March", MarTotalRevenue],
    ["April", AprTotalRevenue],
    ["May", MayTotalRevenue],
    ["June", JunTotalRevenue],
    ["July", JulTotalRevenue],
    ["August", AugTotalRevenue],
    ["September", SepTotalRevenue],
    ["October", OctTotalRevenue],
    ["November", NovTotalRevenue],
    ["December", DecTotalRevenue]
  ];
  return (
    <Chart
      chartType="AreaChart"
      width="100%"
      height="100%"
      data={data}
      options={options}
    />
  );
}
